hello_first:
    path: /
    controller: App\Controller\HelloController::hello

hello_second:
    path: /hello2
    controller: App\Controller\HelloController::hello2

hello_convert:
    path: /convert/{kilometers}
    controller: App\Controller\HelloController::convert
    requirements:
        kilometers: \d+                                         #un caractère chiffre minimun et pas de limit max